[package]
name = "rustlucene-metric"
version = "0.1.0"
edition = "2021"

[dependencies]
rustlucene-core = { path = "../core" }
codec-lucene9 = { path = "../codec-lucene9" }
xxhash-rust = { version = "0.8", features = ["xxh64"] }
parking_lot = "0.12"
tokio = { version = "1", features = ["rt", "sync", "time", "macros"] }

[dev-dependencies]
# 无 tempfile，用 std::env::temp_dir
